######################################################################
# FlowEnvironment Tests Makefile
######################################################################
flowenv-tests-me_reldir := $(flowenv-tests_reldir)/me
flowenv-tests-me_absdir := $(flowenv-tests_absdir)/me

######################################################################
# nfcc compile test
######################################################################
flowenv_tests_me_nfcc_compile_LIST_common = \
 cl0.me0:nfcc_compile.c@$(flowenv-tests-me_absdir)/nfcc_compile.c
flowenv_tests_me_nfcc_compile_DEPS_common += $(flowenv-nfp6000-includes)
flowenv_tests_me_nfcc_compile_NFCCFLAGS_common += \
	-I$(flowenv-me-include_absdir) \
	-I$(flowenv-me-include_reldir)
flowenv_tests_me_nfcc_compile.fw_DESCRIPTION = "FlowEnv nfcc compile test"
$(eval $(call mefw_template,flowenv_tests_me_nfcc_compile,$(flowenv-tests-me_reldir)))


######################################################################
# nfas compile test
######################################################################
flowenv_tests_me_nfas_compile_LIST_common = \
 cl0.me0:nfas_compile.uc@$(flowenv-tests-me_absdir)/nfas_compile.uc
flowenv_tests_me_nfas_compile_DEPS_common += $(flowenv-nfp6000-includes)
flowenv_tests_me_nfas_compile_NFASFLAGS_common += \
	-I$(flowenv-me-include_absdir) \
	-I$(flowenv-me-include_reldir)
flowenv_tests_me_nfas_compile.fw_DESCRIPTION = "FlowEnv nfas compile test"
$(eval $(call mefw_template,flowenv_tests_me_nfas_compile,$(flowenv-tests-me_reldir)))



######################################################################
# Convenience target
######################################################################
flowenv-tests: \
	flowenv_tests_me_nfcc_compile.fw \
	flowenv_tests_me_nfas_compile.fw
