######################################################################
# FlowEnvironment Tests Makefile
######################################################################
flowenv-tests-me_reldir := $(flowenv-tests_reldir)/me
flowenv-tests-me_absdir := $(flowenv-tests_absdir)/me

######################################################################
# nfcc compile test
######################################################################
flowenv_tests_me_nfcc_compile_CHIP = nfp-6xxx
flowenv_tests_me_nfcc_compile_LIST_common = \
	mei0.me0:nfcc_compile.c@$(flowenv-tests-me_absdir)/nfcc_compile.c
flowenv_tests_me_nfcc_compile_DEPS_common += $(flowenv-nfp6000-includes)
flowenv_tests_me_nfcc_compile_NFCCFLAGS_common += \
	-I$(flowenv-me-include_absdir) \
	-I$(flowenv-me-include_reldir) \
	-I$(flowenv-me-lib_absdir)
flowenv_tests_me_nfcc_compile_NFCCFLAGS_common += \
	-Qnctx_mode=8 \
	-Qnn_mode=1 \
	-Qspill=7 \
	-Qperfinfo=32 \
	-Qno_decl_volatile
flowenv_tests_me_nfcc_compile_NFCCSRCS_common += \
	$(flowenv-me-lib_absdir)/nfp/libnfp.c
flowenv_tests_me_nfcc_compile.fw_DESCRIPTION = "FlowEnv nfcc compile test"
$(eval $(call mefw_template,flowenv_tests_me_nfcc_compile,$(flowenv-tests-me_reldir)))


######################################################################
# nfas compile test
######################################################################
flowenv_tests_me_nfas_compile_CHIP = nfp-6xxx
flowenv_tests_me_nfas_compile_LIST_common = \
	mei0.me0:nfas_compile.uc@$(flowenv-tests-me_absdir)/nfas_compile.uc
flowenv_tests_me_nfas_compile_DEPS_common += $(flowenv-nfp6000-includes)
flowenv_tests_me_nfas_compile_NFASFLAGS_common += \
	-I$(flowenv-me-include_absdir) \
	-I$(flowenv-me-include_reldir) \
	-I$(flowenv-me-lib_absdir)
flowenv_tests_me_nfas_compile.fw_DESCRIPTION = "FlowEnv nfas compile test"
$(eval $(call mefw_template,flowenv_tests_me_nfas_compile,$(flowenv-tests-me_reldir)))



######################################################################
# Convenience target
######################################################################
flowenv-tests: \
	flowenv_tests_me_nfcc_compile.fw \
	flowenv_tests_me_nfas_compile.fw
