
/* Standard header file */
#include <assert.h>
#include <nfp.h>
#include <stdint.h>
#include <types.h>

/* Autogenerated header files */
#include <nfp6000/nfp_cls.h>
#include <nfp6000/nfp_ctm.h>
#include <nfp6000/nfp_event.h>
#include <nfp6000/nfp_mac.h>
#include <nfp6000/nfp_me.h>
#include <nfp6000/nfp_pcie.h>
#include <nfp6000/nfp_qc.h>

/* libnet header files */
#include <net/eth.h>
#include <net/gre.h>
#include <net/hdr_ext.h>
#include <net/ip.h>
#include <net/tcp.h>
#include <net/udp.h>

/* libnfp related header files */
#include <nfp/cls.h>
#include <nfp/macstats.h>
#include <nfp/me.h>
#include <nfp/mem_bulk.h>
#include <nfp/mem_pe.h>
#include <nfp/mem_ring.h>
#include <nfp/pcie.h>
#include <nfp/tmq.h>
#include <nfp/xpb.h>

/* libstd related header files */
#include <std/cntrs.h>
#include <std/event.h>
#include <std/hash.h>
#include <std/reg_utils.h>
#include <std/write_alert.h>

/* libpkt related header files */
#include <pkt/pkt.h>

/* liblu related header files */
#include <lu/cam_hash.h>

// /* libblm related header files */
// #include <blm/blm.h>




/*
<yaml>
tests:
# common defines used for all tests, unless overwritten within the test itself
  - name: defaults
# Assembler or compiler flags
    flags:
        - -chip nfp-6xxx 
        - -Qrevision_min=0
        - <-O1, -O2, -Od> -ng
#        - <-O1, -O2, -Od>
        - -Ob1 -W3
        - -Qbigendian -Qnctx=8 -Qspill=1 -Qnctx_mode=8 -Qnn_mode=0 -Qlm_start=0
        - -Zi
# Assembler or compiler includes
    inc:
        - $TOOLCHAIN_INC_DIR/standardlibrary/microc/include
        - $TOOLCHAIN_INC_DIR/flowenv-ng.hg/me/include/
        - $TOOLCHAIN_INC_DIR/flowenv-ng.hg/me/lib/
# Additional files used when compiling microc
    cfiles:
        - $TOOLCHAIN_INC_DIR/standardlibrary/microc/src/rtl.c
        - $TOOLCHAIN_INC_DIR/flowenv-ng.hg/me/lib/nfp/_c/mem_bulk.c
        - $TOOLCHAIN_INC_DIR/flowenv-ng.hg/me/lib/nfp/_c/me.c
        - $TOOLCHAIN_INC_DIR/flowenv-ng.hg/me/lib/nfp/libnfp.c
# Linker flags
    nfld_flags:
        - -chip nfp-6xxx
        - -g
# Linker assignment of list file to ME
    nfld_list:
        - i32.me4:$FNAME.list
# Linker name of nffw (elf) file to generate
    nfld_elf: -elf64 $FNAME.nffw
# Simulation options
    sim:
        - meids:
            - mei0.me4:-1
# Total number of steps to run the simulator
          run: 2000
# The step interval when running the simulator
          stepsize: 20
# The expected result of running a test
    expected_result: True
</yaml>
*/



/* prototypes */
int32_t utfe_lib_build_compile(void);


#ifdef ALL_TEST
    #define UTFE_LIB_BUILD_COMPILE
#endif

//     #define NBI_PKT_PREPEND_BYTES 0

#include "../me/lib/lu/liblu.c"
#include "../me/lib/modscript/libmodscript.c"
#include "../me/lib/net/libnet.c"
#include "../me/lib/nfp/libnfp.c"
#include "../me/lib/pkt/libpkt.c"
// #include "../me/lib/pktdma/libpktdma.c"      // TODO fix warnings
// #include "../me/lib/pktio/libpktio.c"        // TODO fix errors/warnings?
#include "../me/lib/std/libstd.c"


/* main test loop */
void main(void)
{
    uint32_t tests_passed = 0;
    uint32_t tests_failed = 0;

    // only one context
    if ( ctx() != 0)
    {
        return;
    }
    
    // write non-zero value to mailbox0, this to detect if a function does not return 
    // if a function is aborted then all 4 mailboxes have value 0 (specific for non-nti test)
    local_csr_write(local_csr_mailbox0, 2);     // ERROR
    local_csr_write(local_csr_mailbox1, 0);
    local_csr_write(local_csr_mailbox2, 0);
    local_csr_write(local_csr_mailbox3, 0);


#ifdef UTFE_LIB_BUILD_COMPILE
    if (utfe_lib_build_compile() == 0) {
        tests_passed++;
    }  else {
        tests_failed++;
    }
#endif

    /* Use the mailboxes to indicate results from running the test
    * Mailbox0 = 0 for a Pass, else indicates a error condition
    */
    if (tests_failed == 0)
    {
        local_csr_write(local_csr_mailbox0, 0);     // OK
    } else {
        local_csr_write(local_csr_mailbox0, 1);     // ERROR
    }

#ifdef ALL_TEST
    local_csr_write(local_csr_mailbox2, tests_passed);                  // number of test passed
    local_csr_write(local_csr_mailbox3, tests_failed + tests_passed);   // number of test excuted
#endif

}


/*
<yaml>
  - name: utfe_lib_build_compile
    info: Compile std
    summary: This only compiles files in std directory
    defs:
        - UTFE_LIB_BUILD_COMPILE
</yaml>
*/
int32_t utfe_lib_build_compile(void)
{
    // PASS
    return 0;
}





