/*
 * Copyright (C) 2014, Netronome Systems, Inc.  All rights reserved.
 *
 * @file          tests/me/nfas_compile.c
 * @brief         Compile test for nfas header files and libraries
 */


/* Autogenerated header files */
#include <nfp6000/nfp_cls.h>
#include <nfp6000/nfp_event.h>
#include <nfp6000/nfp_me.h>
#include <nfp6000/nfp_pcie.h>
#include <nfp6000/nfp_qc.h>

#include <nfp/nfp.h>

/* Dummy main entry point */
.begin
    halt
.end