/*
 * Copyright (C) 2014-2018, Netronome Systems, Inc.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @file          tests/me/nfas_compile.c
 * @brief         Compile test for nfas header files and libraries
 */


/* Autogenerated header files */
#if (IS_NFPTYPE(__NFP3800))
    #include <nfp3800/nfp_cls.h>
    #include <nfp3800/nfp_ctm.h>
    #include <nfp3800/nfp_event.h>
    #include <nfp3800/nfp_mac.h>
    #include <nfp3800/nfp_me.h>
    #include <nfp3800/nfp_pcie.h>
    #include <nfp3800/nfp_qc.h>
#elif (IS_NFPTYPE(__NFP6000))
    #include <nfp6000/nfp_cls.h>
    #include <nfp6000/nfp_ctm.h>
    #include <nfp6000/nfp_event.h>
    #include <nfp6000/nfp_mac.h>
    #include <nfp6000/nfp_me.h>
    #include <nfp6000/nfp_pcie.h>
    #include <nfp6000/nfp_qc.h>
#else
    #error "Please select valid chip target."
#endif


/* Dummy main entry point */
.begin
    halt
.end