/*
 * Copyright (C) 2014, Netronome Systems, Inc.  All rights reserved.
 *
 * @file          tests/me/nfcc_compile.c
 * @brief         Compile test for nfcc header files and libraries
 */


/* Standard header file */
#include <assert.h>
#include <nfp.h>
#include <stdint.h>
#include <types.h>

/* Autogenerated header files */
#include <nfp6000/nfp_cls.h>
#include <nfp6000/nfp_event.h>
#include <nfp6000/nfp_me.h>
#include <nfp6000/nfp_pcie.h>
#include <nfp6000/nfp_qc.h>

/* libnfp related header files */
#include <nfp/cls.h>
#include <nfp/me.h>
#include <nfp/mem_bulk.h>
#include <nfp/mem_ring.h>

/* libstd related header files */
#include <std/event.h>
#include <std/reg_utils.h>

/* Dummy main entry point */
int
main(void)
{
    for (;;);
    /* NOTREACHED */
}
