/*
 * Copyright (C) 2014, Netronome Systems, Inc.  All rights reserved.
 *
 * @file          tests/me/nfcc_compile.c
 * @brief         Compile test for nfcc header files and libraries
 */


/* Autogenerated header files */
#include <nfp6000/nfp_event.h>
#include <nfp6000/nfp_me.h>
#include <nfp6000/nfp_pcie.h>
#include <nfp6000/nfp_qc.h>


/* Dummy main entry point */
int
main(void)
{
    for (;;);
    /* NOTREACHED */
}
