/*
 * Copyright (C) 2014, Netronome Systems, Inc.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @file          tests/me/nfcc_compile.c
 * @brief         Compile test for nfcc header files and libraries
 */


/* Standard header file */
#include <assert.h>
#include <nfp.h>
#include <stdint.h>
#include <types.h>

/* Autogenerated header files */
#include <nfp6000/nfp_cls.h>
#include <nfp6000/nfp_ctm.h>
#include <nfp6000/nfp_event.h>
#include <nfp6000/nfp_me.h>
#include <nfp6000/nfp_pcie.h>
#include <nfp6000/nfp_qc.h>

/* libnet header files */
#include <net/eth.h>
#include <net/gre.h>
#include <net/ip.h>
#include <net/tcp.h>
#include <net/udp.h>

/* libnfp related header files */
#include <nfp/cls.h>
#include <nfp/me.h>
#include <nfp/mem_bulk.h>
#include <nfp/mem_ring.h>
#include <nfp/pcie.h>
#include <nfp/xpb.h>

/* libstd related header files */
#include <std/cntrs.h>
#include <std/event.h>
#include <std/hash.h>
#include <std/reg_utils.h>
#include <std/write_alert.h>

/* libpkt related header files */
#include <pkt/pkt.h>

/* Dummy main entry point */
int
main(void)
{
    for (;;);
    /* NOTREACHED */
}
